### ISSUE TITLE
[PC] [기사페이지] 하단의 Related / Nearby 컨텐츠 클릭시 top으로 돌아감

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#33]
해당 컨텐츠의 링크로 이동할 수 있도록 수정해주세요.
そのコンテンツのリンクに移動できるように修正してください。

![Screen Shot 2019-06-07 at 12 51 51](https://user-images.githubusercontent.com/51468543/59080341-29d20080-8923-11e9-8edf-ede0815d288b.png)

**Comment by fujimotomiyuki** [comment]
Finish!
