### ISSUE TITLE
[SP] 기사 페이지 리뉴얼시 FOOTER 바뀐 디자인 적용하기

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#35]
- [ ] 모든 페이지: FOOTER 영역 및 FOOTER 이하의 영역이 긴 여백이 생기는 부분을 없애주세요.
すべてのページ: FOOTER領域及びFOOTER以下の領域が長い余白が生じる部分を取り除いてください。

- [ ] 기사 페이지: 리뉴얼시 FOOTER의 영역이 길어지는 부분을 수정하고, 새로 제작된 디자인을 기사 페이지에 적용해 주세요.
すべてのページ: FOOTER領域及びFOOTER以下の領域が長い余白が生じる部分を取り除いてください。

![footer scroll](https://user-images.githubusercontent.com/51468543/59080668-e5476480-8924-11e9-9244-66da15042895.jpg)

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
