### ISSUE TITLE
[SP] 다른 스타일의 Menu 수정

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#36]
- [x] 다른 스타일의 menu가 보이는 페이지가 있습니다. (url에 map이 들어가는 페이지, contact, privacy policy 등) menu의 스타일을 통일해 주세요.
他のスタイルのmenuが見えるページがあります。 (urlにmapが入るページ,contact,privacy policyなど)menuのスタイルを統一してください。
https://www.japankuru.com/sp/kr/gourumet/

![map-menu](https://user-images.githubusercontent.com/51468543/59080989-bdf19700-8926-11e9-86c0-eba943b20ac6.jpg)

**Comment by fujimotomiyuki** [comment]
map gourumet privacy contact の修正は終わりました。
他のページで旧メニューを見つけたら教えてください

**Comment by gracemj** [comment]
👍
