### ISSUE TITLE
[PC/SP] Top-Event Calendar

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#39]
- [x] top 페이지에서 표시되는 이벤트 캘린더. 표시되는 이벤트는 오늘 날짜를 기준으로 가장 가까운 이벤트부터 표시되어야 합니다. 일람 표시 기준을 수정해주세요.
topページに表示されるイベントカレンダー。表示されるイベントは、今日の日付を基準に最も近いイベントから表示されます。一覧表示の基準を変更してください。

![Screen Shot 2019-06-07 at 14 51 13](https://user-images.githubusercontent.com/51468543/59083857-f2b81b00-8933-11e9-9fa8-bc63819c1ead.png)

**Comment by fujimotomiyuki** [comment]
Finish!
イベント記事の下のLeatest Event も同じ順番に変更しました

**Comment by JasonSeong** [comment]
ありがとうございます !
