### ISSUE TITLE
[SP/PC] Event Calendar 페이지에서의 월 < > 버튼

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#40]
- [ ] Event Calendar 에는 이벤트 포스트 기간에 해당하는 모든 월이 표시되어야 합니다. 해당 부분을 확인하고 수정해주세요. 현재 2019년 10월, 11월 이벤트 포스트도 게시되었지만, 9월 이후의 월을 선택할 수 없도록 되어 있습니다.

Event Calendarには、イベントのポスト期間に該当するすべての月に表示されます。該当部分を確認して修正してください。現在2019年10月、11月のイベントのポストも公開されたが、9月以降の月を選択することができないようになっています。

![Screen Shot 2019-06-07 at 14 51 44](https://user-images.githubusercontent.com/51468543/59083967-580c0c00-8934-11e9-9cd5-ac920b376758.png)

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
