### ISSUE TITLE
[SP] 메뉴 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#43]
- [x] 햄버거 아이콘 -->닫기 아이콘으로 변경
ハンバーガーアイコン--"閉じるアイコン"に変更

- [x] Destination/ Thing to do 텍스트 컬러 #757575
Destination/Thing to doテキストカラー#757575

- [x] Event Calendar, Featured video, booking 텍스트 왼쪽 패딩 위의 Things to do 와 같게
Event Calendar, Featured video, booking テキスト 左パディング上のThings to doのように

![image](https://user-images.githubusercontent.com/14939610/59085262-00bc6a80-8939-11e9-859a-031e618b2fd5.png)
![image](https://user-images.githubusercontent.com/14939610/59085695-770d9c80-893a-11e9-8777-c3c38d569f0f.png)

![image](https://user-images.githubusercontent.com/14939610/59085306-1cc00c00-8939-11e9-997e-70ca6a6ded00.png)

**Comment by fujimotomiyuki** [comment]
Finish!
