### ISSUE TITLE
[SP]top page 빅배너 아래 제목 스타일 조정

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#44]
- [ ] 제목 두줄 ...으로 조정. 아래 여백 줄이기
タイトル二列に調整。以下の余白減らすこと

![image](https://user-images.githubusercontent.com/14939610/59086474-c81e9000-893c-11e9-9a2d-8feb61785be2.png)

**Comment by fujimotomiyuki** [comment]
FInish

**Comment by gracemj** [comment]
👍
