### ISSUE TITLE
[SP] Things to do 텍스트 아래 패딩 조정

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#45]
![image](https://user-images.githubusercontent.com/14939610/59086800-c2757a00-893d-11e9-8f2c-fe1bc9a549a0.png)

- [ ] Things to do 텍스트 아래 패딩 조정, 다른 섹션타이틀과 동인한 패딩간격으로 조정해주세요. 지금은 많이 넓어졌습니다.
Things to doテキストの下にあるパディング調整,他のセクションタイトルと同人なパディング間隔で調整してください。 今はだいぶ広くなりました。

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
