### ISSUE TITLE
[SP]Featured Videos 첫번째 비디오 리스트 아래 여백 조정

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#46]
![image](https://user-images.githubusercontent.com/14939610/59086939-462f6680-893e-11e9-822a-021b58aededa.png)
![image](https://user-images.githubusercontent.com/14939610/59087625-2ef17880-8940-11e9-9f7a-4a62db0414c2.png)

- [x]  첫번째 비디오 리스트 아래 여백 조정, 텍스트 길이에 따라 유동적으로 같은 패딩 간격유지
最初のビデオリストの下での余白調整,テキストの長さによって流動的に同じパディング間隔維持

- [x] 비디오 이미지 안의 플레이 아이콘 중앙 정렬, 지금 조금 올라가 보입니다.
ビデオイメージの中のプレイアイコンの中央整列,今少し上がって見えます。

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
