### ISSUE TITLE
[SP] 메이킹 필름 섹션 스타일 수정

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#47]
![image](https://user-images.githubusercontent.com/14939610/59087695-62cc9e00-8940-11e9-9f71-facf5f2f36ef.png)
![image](https://user-images.githubusercontent.com/14939610/59088148-9eb43300-8941-11e9-8ebf-3b9004025ec4.png)

- [x] 제플린 디자인 확인 /ジェフリンデザイン確認

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
