### ISSUE TITLE
[SP] 언어셀렉박스 텍스트 

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#49]
![image](https://user-images.githubusercontent.com/14939610/59088396-4e89a080-8942-11e9-8903-84797c00b850.png)
 

- [x]  English 첫글자만 대문자로 / Englishの最初の文字だけ 大文字に

- [x] 베트남어 첫글자는 대문자로 / ベトナム語の最初の文字は大文字で

**Comment by fujimotomiyuki** [comment]
Finish

**Comment by gracemj** [comment]
👍
