### ISSUE TITLE
[SP] 풋터스타일 

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#50]
![image](https://user-images.githubusercontent.com/14939610/59088676-1cc50980-8943-11e9-80c8-7d1d98983442.png)
![image](https://user-images.githubusercontent.com/14939610/59089213-809c0200-8944-11e9-9d21-855c1d8dc951.png)

- [x] 아래  아이콘 아래 메뉴와 텍스트 왼쪽  패딩 조정
下のアイコンの下のメニューとテキスト左パディング調整

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
