### ISSUE TITLE
[SP]태국어 버전 Map of Japan 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#53]
![image](https://user-images.githubusercontent.com/14939610/59090702-7976f300-8948-11e9-8e89-e82dac8aefc1.png)
![image](https://user-images.githubusercontent.com/14939610/59090710-7ed43d80-8948-11e9-80f1-d7eb1f9e3a37.png)
![image](https://user-images.githubusercontent.com/14939610/59090719-8693e200-8948-11e9-8a1e-6aebfe562256.png)

- [x] 지역 텍스트박스에 텍스트가 잘리는 문제
地元のテキストボックスにテキストが切られる問題

**Comment by fujimotomiyuki** [comment]
Finish

**Comment by gracemj** [comment]
👍
