### ISSUE TITLE
[SP]셀렉박스 스타일

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#54]
![image](https://user-images.githubusercontent.com/14939610/59091483-6533f580-894a-11e9-9acb-5d78197af8d9.png)

- [x] 펼쳤을때 화살표 방향 반대로 바꿔주세요.
広げた時,アイコン矢印の方向反対に変えてください。

**Comment by fujimotomiyuki** [comment]
Finish

**Comment by gracemj** [comment]
👍
