### ISSUE TITLE
[PC] 내용 없는 빈 이벤트가 표시되고 있습니다.

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#58]
TOP페이지에 이벤트 내용이 입력되지 않은 빈 껍데기가 표시되고 있습니다.

TOPページにイベント内容が入力されていない空の殻が表示されています。

![Screen Shot 2019-06-11 at 14 10 04](https://user-images.githubusercontent.com/51468543/59245430-c3671e00-8c53-11e9-92b5-7ebec8677b05.png)

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by JasonSeong** [comment]
確認しました！
ありがとうございます。
