### ISSUE TITLE
한국어버전 Things to do "View All" 한국어로 변경

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#59]
- [x] 한국어버전 Things to do "View All"-->"모두 보기"로 변경
]韓国語バージョンのThings to do"View All"-->"모두 보기"に変更
**
![image](https://user-images.githubusercontent.com/14939610/59245719-daf2d680-8c54-11e9-945a-0d0dcfd15609.png)
**

**Comment by fujimotomiyuki** [comment]
Finish

**Comment by gracemj** [comment]
👍
