### ISSUE TITLE
[PC] 텍스트 좌측간격  줄이기

### ISSUE THREAD

**Issue by gracemj** [gracemj/JapanKuru#62]
- [x] 텍스트 좌측간격  줄이기
テキストの左の間隔を減らす
![image](https://user-images.githubusercontent.com/14939610/59315346-59528580-8cf4-11e9-9e51-23dc06ccfd78.png)

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
:
