### ISSUE TITLE
CMSの動画一覧に登録した映像が、Topページでは表示されていません。

### ISSUE THREAD

**Issue by JasonSeong** [gracemj/JapanKuru#64]
CMSの動画一覧に登録した映像が、Topページでは表示されていません。

CMS에서 동영상 일람에 영상을 등록하여 공개했지만, Top페이지에서는 표시되지 않고 있습니다. (비디오 페이지에서는 표시되고 있습니다)

![Screen Shot 2019-06-13 at 11 29 07](https://user-images.githubusercontent.com/51468543/59399369-b1f65100-8dce-11e9-937a-051aac7ded81.png)
![Screen Shot 2019-06-13 at 11 29 56](https://user-images.githubusercontent.com/51468543/59399370-b1f65100-8dce-11e9-89f8-9db7e0a708fc.png)

**Comment by fujimotomiyuki** [comment]
Finish!

**Comment by gracemj** [comment]
👍
